openapi: 3.0.3
info:
  version: 1.0.0
  title: 'Bank API'
  description: 'Bank API Spec'
tags:
  - name: Bank
    description: Bank spec
paths:
  /customers:
    get:
      summary: 'Retrieve a list of bank customers'
      description: Get request
      operationId: 'getCustomers'
      tags:
        - Bank
      responses:
        '200':
          $ref: '#/components/responses/ListCustomersResponse'
    post:
      summary: 'Add a new Customer'
      description: 'Endpoint to add a new Customer to the DB'
      operationId: 'addCustomer'
      tags:
        - Bank
      requestBody:
        $ref: '#/components/requestBodies/AddCustomerRequest'
      responses:
        '200':
          $ref: '#/components/responses/CustomerModelResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
  /customers/{customer-id}:
    get:
      summary: 'Retrieve a customer for a given ID'
      description: Get request
      operationId: 'getCustomerByID'
      tags:
        - Bank
      parameters:
        - $ref: '#/components/parameters/customer-id'
      responses:
        '200':
          $ref: '#/components/responses/CustomerModelResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
  /bankaccounts:
    get:
      summary: 'Retrieve a list of bank accounts'
      description: Get request
      operationId: 'getBankAccounts'
      tags:
        - Bank
      responses:
        '200':
          $ref: '#/components/responses/ListBankAccountsResponse'
  /bankaccounts/{bankAccountNumber}:
    get:
      summary: 'Retrieve a Bank Account for a given Bank Account Number'
      description: Get request
      operationId: 'getBankAccountByID'
      tags:
        - Bank
      parameters:
        - $ref: '#/components/parameters/bankAccountNumber'
      responses:
        '200':
          $ref: '#/components/responses/BankAccountIdResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
components:
  requestBodies:
    AddCustomerRequest:
      description: OK
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/addCustomerModel'
  responses:
    ListCustomersResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/customersList'
    CustomerModelResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/customerModel'
    ListBankAccountsResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/bankAccountsList'
    BankAccountIdResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/bankAccountModel'
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorModel'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorModel'
  schemas:
    customersList:
      description: A list of the Customer objects
      type: array
      items:
        $ref: '#/components/schemas/customerModel'
    customerModel:
      type: object
      description: Links to the Customer.java class via the pom.xml
    addCustomerModel:
      type: object
      description: Links to the Customer.java class via the pom.xml
      properties:
        customerName:
          type: string
          example: 'John Doe'
        customerAge:
          type: integer
          example: 30
    bankAccountsList:
      description: A list of the Bank Account objects
      type: array
      items:
        $ref: '#/components/schemas/bankAccountModel'
    bankAccountModel:
      type: object
      description: Links to the BankAccount.java class via the pom.xml
    errorModel:
      type: object
      description: Links to the BankError.java class via the pom.xml
  parameters:
    customer-id:
      name: customer-id
      in: path
      schema:
        type: integer
      required: true
      description: Customer ID
      example: 123
    bankAccountNumber:
      name: bankAccountNumber
      in: path
      schema:
        type: integer
      required: true
      description: Bank Account Number
      example: 123