openapi: 3.0.3
info:
  version: 1.0.0
  title: 'Bank API'
  description: 'Bank API Spec'
tags:
  - name: Bank
    description: Bank spec
paths:
  /customers:
    get:
      summary: 'Retrieve a list of bank customers'
      description: Get request
      operationId: 'getCustomers'
      tags:
        - Bank
      responses:
        '200':
          $ref: '#/components/responses/ListCustomersResponse'
  /customers/{customer-id}:
    get:
      summary: 'Retrieve a customer for a given ID'
      description: Get request
      operationId: 'getCustomerByID'
      tags:
        - Bank
      parameters:
        - $ref: '#/components/parameters/customer-id'
      responses:
        '200':
          $ref: '#/components/responses/CustomerIdResponse'
  /bankaccounts:
    get:
      summary: 'Retrieve a list of bank accounts'
      description: Get request
      operationId: 'getBankAccounts'
      tags:
        - Bank
      responses:
        '200':
          $ref: '#/components/responses/ListBankAccountsResponse'
components:
  responses:
    ListCustomersResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/customersList'
    CustomerIdResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/customerModel'
    ListBankAccountsResponse:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/bankAccountsList'
  schemas:
    customersList:
      description: A list of the Customer objects
      type: array
      items:
        $ref: '#/components/schemas/customerModel'
    customerModel:
      type: object
      description: Links to the Customer.java class via the pom.xml
    bankAccountsList:
      description: A list of the Bank Account objects
      type: array
      items:
        $ref: '#/components/schemas/bankAccountModel'
    bankAccountModel:
      type: object
      description: Links to the BankAccount.java class via the pom.xml
  parameters:
    customer-id:
      name: customer-id
      in: path
      schema:
        type: integer
      required: true
      description: Customer ID
      example: 123