


INSERT INTO Customer(CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_AGE)
VALUES (1, 'John Smith', 48);

INSERT INTO Customer(CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_AGE)
VALUES (2, 'Jack Jones', 23);

INSERT INTO Customer(CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_AGE)
VALUES (3, 'Steve Byrne', 62);


INSERT INTO Bank_Account(ACCOUNT_ID, ACCOUNT_TYPE, CUSTOMER_ID)
VALUES (123, 'Current', 1);

INSERT INTO Bank_Account(ACCOUNT_ID, ACCOUNT_TYPE, CUSTOMER_ID)
VALUES (456, 'Current', 2);

INSERT INTO Bank_Account(ACCOUNT_ID, ACCOUNT_TYPE, CUSTOMER_ID)
VALUES (789, 'Current', 3);